version: '3.8'

volumes:
 wordpress_volume:
  driver: local
  driver_opts:
   type: none
   device: /home/mbelrhaz/data/html
   o: bind
 mariadb_vol:
  driver: local
  driver_opts:
   type: none
   device: /home/mbelrhaz/data/db
   o: bind

services:
 mariadb:
  build:
   context: ./mariadb
   dockerfile: Dockerfile
  ports:
   - "3306"
  environment:
   MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
   MYSQL_DATABASE: $MYSQL_DATABASE
   MYSQL_USER: $MYSQL_USER
   MYSQL_PASSWORD: $MYSQL_PASSWORD
  restart: on-failure
  volumes:
   - mariadb_vol:/var/lib/mysql
  networks:
   - app-network
 wordpress:
  depends_on:
   - mariadb
  build:
   context: ./wordpress
   dockerfile: Dockerfile
  ports:
   - "9000"
  environment:
   WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
   MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
   WORDPRESS_DB_USER: $WORDPRESS_DB_USER
   WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
   WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
   WORDPRESS_TABLE_PREFIX: $WORDPRESS_TABLE_PREFIX
  volumes:
   - wordpress_volume:/var/www/html
  networks:
   - app-network
  restart: on-failure
 nginx:
  depends_on:
   - wordpress
  build:
   context: ./nginx
   dockerfile: Dockerfile
  ports:
   - "443:443"
  volumes:
   - wordpress_volume:/var/www/html
  networks:
   - app-network
  restart: on-failure

networks:
 app-network:
  driver: bridge

