version: '3.8'

volumes:
 wordpress_volume:
  driver: local
  driver_opts:
   type: none
   device: /data/html
   o: bind
 mariadb_vol:
  driver: local
  driver_opts:
   type: none
   device: /var/local
   o: bind

services:
 mariadb:
  build:
   context: ./mariadb
   dockerfile: Dockerfile
  ports:
   - "3306"
  environment:
   MYSQL_ROOT_PASSWORD: root_password
   MYSQL_DATABASE: db_name
   MYSQL_USER: user_name
   MYSQL_PASSWORD: user_password
  restart: always
  volumes:
   - mariadb_vol:/var/lib/mysql
  networks:
   - app-network
 wordpress:
  depends_on:
   - mariadb
  build:
   context: ./wordpress
   dockerfile: Dockerfile
  ports:
   - "9000:9000"
  environment:
   WORDPRESS_DB_HOST: mariadb:3306
   MYSQL_ROOT_PASSWORD: root_password
   WORDPRESS_DB_USER: user_name
   WORDPRESS_DB_PASSWORD: user_password
   WORDPRESS_DB_NAME: db_name
   WORDPRESS_TABLE_PREFIX: wp_
  volumes:
   - wordpress_volume:/var/www/html
  networks:
   - app-network
  restart: always
 nginx:
  depends_on:
   - wordpress
  build:
   context: ./nginx
   dockerfile: Dockerfile
  ports:
   - "443:443"
  volumes:
   - wordpress_volume:/var/www/html
  networks:
   - app-network

networks:
 app-network:
  driver: bridge

