#!/bin/bash

echo "********CONFIGURING MARIADB********"
/usr/bin/mysql_install_db --user=mysql
service mariadb start
mysqladmin -u root password ${MYSQL_ROOT_PASSWORD}
mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};"
mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "CREATE USER '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';"
mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* to '${MYSQL_USER}'@'%'; \
FLUSH PRIVILEGES;"
service mariadb stop
/usr/bin/mysqld_safe --datadir="/var/lib/mysql"
