#!/bin/bash

echo "super I'm here"
/usr/bin/mysql_install_db --user=mysql
service mariadb start
echo "YOUHOU"
mysqladmin -u root password ${MYSQL_ROOT_PASSWORD}
mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE IF NOT EXISTS hoho;"
mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};"
#CREATE DATABASE '${MYSQL_DATABASE}';\
#CREATE USER '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}'; \
#GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* to '${MYSQL_USER}'@'%'; \
#FLUSH PRIVILEGES;"
service mariadb stop
/usr/bin/mysqld_safe --datadir="/var/lib/mysql"
